#!/usr/bin/env bash

yosys -p "synth_ice40 -top top -json top.json" top.v uart_trx.v pll_48mhz.v

nextpnr-ice40 --hx8k --pcf ice40hx8k.pcf --json top.json --asc top.asc

icepack top.asc top.bin

iceprog top.bin
